-- ============================================================
--  SEED BECAS – Ejecutar en SQL Editor de Supabase
--  Crea la tabla de becas y vuelca los 20 registros iniciales.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.becas (
    id SERIAL PRIMARY KEY,
    nombre TEXT NOT NULL,
    entidad TEXT NOT NULL,
    tipo TEXT,
    region TEXT,
    area TEXT,
    importe JSONB, -- Se guarda como objeto { "min": X, "max": Y }
    deadline DATE,
    url TEXT,
    descripcion TEXT,
    requisitos JSONB,
    etiquetas JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Vaciar la tabla por si ya se había ejecutado
TRUNCATE TABLE public.becas RESTART IDENTITY CASCADE;

-- Insertar los 20 registros estáticos
INSERT INTO public.becas (nombre, entidad, tipo, region, area, importe, deadline, url, descripcion, requisitos, etiquetas) VALUES
('Beca 6000', 'Junta de Andalucía', 'bachillerato', 'Andalucía', 'Cualquier área', '{"min": 6000, "max": 6000}', '2026-10-01', 'https://www.juntadeandalucia.es/educacion/portals/web/becas-y-ayudas', 'Ayuda directa de 6.000 € anuales para estudiantes de Bachillerato o Ciclos Formativos de Grado Medio con escasos recursos para evitar el abandono escolar.', '["Estar matriculado en Bachillerato o CFGM", "Renta familiar < 11.939 €", "Residencia en Andalucía"]', '["junta", "bachillerato", "fp", "renta", "6000"]'),
('Beca Adriano', 'Junta de Andalucía', 'bachillerato', 'Andalucía', 'Cualquier área', '{"min": 1500, "max": 3000}', '2026-10-15', 'https://www.juntadeandalucia.es/educacion/portals/web/becas-y-ayudas', 'Becas para alumnos de 2º Bachillerato, CFGM, CFGS, enseñanzas artísticas y deportivas con escasos recursos económicos.', '["Matriculado en 2º Bach., CFGM o CFGS", "Renta familiar baja", "Residencia en Andalucía"]', '["junta", "adriano", "bachillerato", "fp", "artístico", "deportivo"]'),
('Beca Segunda Oportunidad', 'Junta de Andalucía', 'formacion', 'Andalucía', 'Cualquier área', '{"min": 400, "max": 400}', '2026-05-31', 'https://www.juntadeandalucia.es/educacion/portals/web/becas-y-ayudas', 'Para jóvenes de 18 a 24 años que abandonaron el sistema educativo sin titulación de Secundaria, facilitando su reincorporación.', '["18 a 24 años", "Sin titulación de ESO", "Residencia en Andalucía", "No trabajar a jornada completa"]', '["junta", "segunda oportunidad", "jóvenes", "ESO", "inserción"]'),
('Ayuda Acreditación Idiomas B1/B2', 'Junta de Andalucía', 'idiomas', 'Andalucía', 'Idiomas', '{"min": 300, "max": 300}', '2026-03-28', 'https://www.juntadeandalucia.es/educacion/portals/web/becas-y-ayudas/idiomas', 'Ayuda de 300 € para cubrir el coste de la acreditación oficial de los niveles B1 o B2 de idiomas extranjeros.', '["Ser estudiante en Andalucía", "Renta familiar media-baja", "No haber obtenido esta ayuda antes"]', '["junta", "idiomas", "b1", "b2", "inglés", "certificado"]'),
('Beca MEC – Estudios Universitarios', 'Ministerio de Educación', 'universitaria', 'Nacional', 'Cualquier área', '{"min": 300, "max": 6000}', '2026-10-15', 'https://www.becaseducacion.gob.es', 'Becas generales para estudios de grado en universidades públicas. Incluyen exención de tasas y cuantías fijas y variables según renta.', '["Matrícula mínima 60 créditos", "Rendimiento académico mínimo", "Renta familiar por tramos", "Universidad pública"]', '["MEC", "ministerio", "universitaria", "grado", "renta", "tasas"]'),
('Beca MEC – Máster Habilitante', 'Ministerio de Educación', 'master', 'Nacional', 'Cualquier área', '{"min": 500, "max": 3000}', '2026-11-01', 'https://www.becaseducacion.gob.es', 'Ayudas para cursar estudios de máster universitario habilitante para profesiones reguladas en universidades públicas.', '["Máster habilitante en universidad pública", "Renta familiar por tramos", "Matrícula mínima 30 créditos"]', '["MEC", "ministerio", "máster", "habilitante", "postgrado"]'),
('Erasmus+ Estudios', 'Comisión Europea / Universidad', 'movilidad', 'Nacional', 'Cualquier área', '{"min": 400, "max": 700}', '2026-04-15', 'https://www.erasmusplus.gob.es', 'Beca mensual para realizar un semestre o año académico en una universidad europea. Importe varía por país de destino (400–700 €/mes).', '["Matriculado en universidad española", "Nivel B2 idioma destino", "Expediente académico mínimo"]', '["Erasmus", "movilidad", "internacional", "europeo", "intercambio"]'),
('Fundación La Caixa – Posgrado Nacional', 'Fundación La Caixa', 'master', 'Nacional', 'Cualquier área', '{"min": 16000, "max": 26000}', '2026-03-22', 'https://fundacionlacaixa.org/becas', 'Becas de alto impacto para cursar estudios de posgrado en las mejores universidades de España y el mundo.', '["Grado finalizado con nota alta", "Perfil de liderazgo y compromiso social", "Buenas competencias en inglés"]', '["La Caixa", "fundación", "posgrado", "máster", "doctorado", "excelencia"]'),
('Fundación Carolina – Posgrado Iberoamérica', 'Fundación Carolina', 'master', 'Nacional', 'Cualquier área', '{"min": 12000, "max": 18000}', '2026-04-30', 'https://www.fundacioncarolina.es/becas', 'Becas de movilidad para ciudadanos de Iberoamérica y España para realizar estudios de posgrado y perfeccionamiento profesional.', '["Titulado universitario", "Ciudadanía española o iberoamericana", "Nivel C1 de español"]', '["Carolina", "fundación", "posgrado", "iberoamérica", "investigación"]'),
('Becas FPI – Investigación', 'Ministerio de Ciencia', 'investigacion', 'Nacional', 'Ciencia y Tecnología', '{"min": 16000, "max": 22000}', '2026-05-15', 'https://www.ciencia.gob.es/becas-fpi', 'Becas predoctorales para la formación de personal investigador vinculadas a proyectos financiados por el Plan Estatal de I+D+i.', '["Título de máster o equivalente", "Vinculación a un proyecto de investigación financiado", "Expediente excelente"]', '["FPI", "investigación", "doctorado", "ciencia", "predoctoral"]'),
('Beca Transporte Escolar', 'Junta de Andalucía', 'bachillerato', 'Andalucía', 'Cualquier área', '{"min": 200, "max": 800}', '2026-09-15', 'https://www.juntadeandalucia.es/educacion/portals/web/becas-y-ayudas/transporte', 'Ayudas para sufragar los gastos de transporte a centros educativos para alumnos de Bachillerato y FP que residan lejos del centro.', '["Residir a más de 3 km del centro", "Matriculado en Bach. o FP en Andalucía", "Renta familiar limitada"]', '["junta", "transporte", "bachillerato", "fp", "distancia"]'),
('Beca Comedor Escolar', 'Junta de Andalucía', 'primaria', 'Andalucía', 'Cualquier área', '{"min": 300, "max": 600}', '2026-06-30', 'https://www.juntadeandalucia.es/educacion/portals/web/becas-y-ayudas/comedor', 'Ayudas para el uso del servicio de comedor en colegios públicos de Andalucía para familias con dificultades económicas.', '["Alumnado de infantil y primaria", "Centro con comedor escolar", "Renta familiar baja"]', '["junta", "comedor", "infancia", "primaria", "vulnerabilidad"]'),
('Fulbright – Estudios en EE.UU.', 'Comisión Fulbright España', 'movilidad', 'Nacional', 'Cualquier área', '{"min": 15000, "max": 30000}', '2026-06-01', 'https://fulbright.es/becas', 'Becas para españoles que deseen cursar posgrado, realizar investigación o impartir docencia en universidades de EE.UU.', '["Ciudadanía española", "Licenciatura/Grado finalizado", "Nivel C1 de inglés", "CV sólido"]', '["Fulbright", "EE.UU.", "movilidad", "investigación", "doctorado", "inglés"]'),
('Plan Propio – Universidad de Sevilla', 'Universidad de Sevilla', 'universitaria', 'Andalucía', 'Cualquier área', '{"min": 500, "max": 2000}', '2026-05-30', 'https://www.us.es/becas', 'Becas propias de la Universidad de Sevilla para movilidad nacional, colaboración en proyectos y apoyo al estudio para alumnos de la US.', '["Matriculado en la Universidad de Sevilla", "Expediente académico según beca", "Solicitud en el portal de la US"]', '["Sevilla", "US", "movilidad", "colaboración", "universitaria"]'),
('Beca Fundación Cajasol', 'Fundación Cajasol', 'universitaria', 'Andalucía', 'Cualquier área', '{"min": 2000, "max": 5000}', '2026-04-20', 'https://fundacioncajasol.com/becas', 'Ayudas al estudio para universitarios andaluces de renta baja que cursen estudios de grado en universidades públicas de Andalucía.', '["Matriculado en universidad pública andaluza", "Renta familiar baja", "Residencia habitual en Andalucía"]', '["Cajasol", "fundación", "universitaria", "Andalucía", "renta"]'),
('Beca Iberoamérica – Jóvenes Profesores', 'Santander Universidades', 'movilidad', 'Nacional', 'Educación', '{"min": 4000, "max": 6000}', '2026-06-15', 'https://www.becas-santander.com', 'Programa de movilidad para jóvenes docentes universitarios e investigadores entre España y Latinoamérica.', '["Docente o investigador universitario", "Menos de 35 años", "Proyecto de movilidad justificado"]', '["Santander", "movilidad", "iberoamérica", "docentes", "investigación"]'),
('Beca Enseñanzas Artísticas Superiores', 'Ministerio de Educación', 'artistica', 'Nacional', 'Arte y Diseño', '{"min": 300, "max": 3000}', '2026-10-20', 'https://www.becaseducacion.gob.es/becas-y-ayudas/estudiantes/no-universitarias.html', 'Becas para alumnado matriculado en enseñanzas artísticas superiores (conservatorio, escuela de arte, diseño, etc.).', '["Matriculado en enseñanzas artísticas superiores", "Renta familiar por tramos", "Centro público"]', '["MEC", "artístico", "diseño", "música", "conservatorio", "artes"]'),
('Beca FP Dual – Junta de Andalucía', 'Junta de Andalucía', 'fp', 'Andalucía', 'Formación Profesional', '{"min": 500, "max": 1500}', '2026-09-01', 'https://www.juntadeandalucia.es/educacion/portals/web/fp/fp-dual', 'Ayudas para alumnado que curse ciclos de FP en modalidad dual, combinando formación en centro educativo y empresa.', '["Matriculado en FP Dual en Andalucía", "Empresa colaboradora asignada", "Renta familiar baja o media"]', '["junta", "FP", "dual", "empresa", "formación profesional"]'),
('Ayuda Libros y Material Escolar', 'Junta de Andalucía', 'primaria', 'Andalucía', 'Cualquier área', '{"min": 100, "max": 250}', '2026-07-15', 'https://www.juntadeandalucia.es/educacion/portals/web/becas-y-ayudas/libros', 'Ayudas al Banco de Libros y para la adquisición de material escolar para alumnado de Primaria, ESO y Bachillerato en Andalucía.', '["Centro educativo público en Andalucía", "Solicitud en el centro antes del plazo", "Renta familiar por tramos"]', '["junta", "libros", "material", "escolar", "banco", "primaria", "ESO"]'),
('MAEC-AECID – Posgrado Español', 'Ministerio de Asuntos Exteriores (AECID)', 'master', 'Nacional', 'Cualquier área', '{"min": 10000, "max": 18000}', '2026-04-01', 'https://www.aecid.es/becas', 'Becas para que extranjeros y españoles residentes en el exterior realicen estudios de posgrado en universidades españolas.', '["Ciudadanía española viviendo en el extranjero o extranjero con vínculo con España", "Grado universitario", "Nivel B2 español"]', '["AECID", "MAEC", "posgrado", "exterior", "máster", "internacional"]');

-- Habilitar permisos de lectura públicos para que el backend pueda seleccionar sin problemas
ALTER TABLE public.becas ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Lectura publica_becas" ON public.becas FOR SELECT USING (true);
